#Home, pagina de inicio
homeController:
  path: /
  controller: App\Infrastructure\Controller\HomeController::homeAction

static-aviso-legal:
  path: /aviso-legal/
  controller: App\Infrastructure\Controller\StaticController::avisoLegalAction
  methods: [GET]

static-politica-privacidad:
  path: /politica-de-privacidad/
  controller: App\Infrastructure\Controller\StaticController::privacidadAction
  methods: [GET]

static-terminos-y-condiciones:
  path: /terminos-y-condiciones-de-uso/
  controller: App\Infrastructure\Controller\StaticController::terminosYCondicionesAction
  methods: [GET]

static-faq:
  path: /faq/
  controller: App\Infrastructure\Controller\StaticController::faqAction
  methods: [GET]

contacto-faq:
  path: /contacto/
  controller: App\Infrastructure\Controller\StaticController::contactoAction
  methods: [GET]

soporte-faq:
  path: /soporte/
  controller: App\Infrastructure\Controller\StaticController::soporteAction
  methods: [GET]