#Nuevo Menu Carta
panel-new-menu:
  path: /panel/editar-informacion-local/{local}/nuevo-menu
  controller: App\Infrastructure\Controller\MenuController::newMenuOfLocalAction
  methods: [GET, POST]
#ver Menus
panel-show-menu:
  path: /panel/editar-informacion-local/{local}/ver-menus
  controller: App\Infrastructure\Controller\MenuController::showMenuOfLocalAction
  methods: [GET, POST]  
#editar Menus
panel-edit-menu-and-show-products:
  path: /panel/editar-informacion-local/{local}/editar-menu/{menuId}
  controller: App\Infrastructure\Controller\MenuController::editMenuOfLocalAction
  methods: [GET, POST]
#borrar Menus
panel-delete-menu:
  path: /panel/editar-informacion-local/{local}/borrar-menu/{menuId}
  controller: App\Infrastructure\Controller\MenuController::deleteMenuOfLocalAction
  methods: [GET, POST]        
#borrar foto de Menus
panel-edit-menu-delete-photos:
  path: /panel/editar-informacion-local/{local}/editar-menu/{menuId}/-borrar-foto
  controller: App\Infrastructure\Controller\MenuController::editMenuForDeletePhotoOfLocalAction
  methods: [GET, POST]  