#editar Producto
panel-edit-product:
  path: /panel/editar-informacion-local/{local}/editar-menu/{menuId}/editar-producto/{productoId}
  controller: App\Infrastructure\Controller\ProductController::editProductOfMenuAction
  methods: [GET, POST]    
#editar Producto solitario
panel-edit-product-alone:
  path: /panel/editar-informacion-local/{local}/editar-producto/{productoId}
  controller: App\Infrastructure\Controller\ProductController::editProductAloneAction
  methods: [GET, POST]     
#borrar Producto
panel-delete-product:
  path: /panel/editar-informacion-local/{local}/editar-menu/{menuId}/borrar-producto/{productoId}
  controller: App\Infrastructure\Controller\ProductController::deleteProductOfLocalAction
  methods: [GET, POST]     
#Nuevo producto asociado a un menu
panel-new-product:
  path: /panel/editar-informacion-local-{local}/menu-{menuId}/nuevo-producto
  controller: App\Infrastructure\Controller\ProductController::newProductAction
  methods: [GET, POST]
#Nuevo producto solo
panel-new-product-alone:
  path: /panel/editar-informacion-local/{local}/nuevo-producto
  controller: App\Infrastructure\Controller\ProductController::newProductAloneAction
  methods: [GET, POST]
#borrar Producto sin menu
panel-delete-product-alone:
  path: /panel/editar-informacion-local/{local}/borrar-producto/{productoId}
  controller: App\Infrastructure\Controller\ProductController::deleteProductAloneOfLocalAction
  methods: [GET, POST]   